#!/usr/bin/env bash

source ~/.bashrc

cd /app

# dependencies
mix deps.get --only prod
MIX_ENV=prod mix compile

# compile assets
MIX_ENV=prod mix assets.deploy

# build release
mix phx.gen.release
MIX_ENV=prod mix release
cp _build/prod/*.gz /app/releases
