#!/usr/bin/env bash

VERSION=0.1.0

# Rockylinus basline image
docker build --force-rm --tag exdoc_builder:$VERSION .

# various options here
case "$1" in
  "c")
    # get a bash shell in a running container with acutal source code
    # ./bash c (like c for console)
    docker run --rm -v $PWD/releases:/app/releases -it exdoc_builder:$VERSION bash
    exit 0;;
  *)
    # builds app with actual source code, find release in releases folder
    docker run --rm -v $PWD/releases:/app/releases exdoc_builder:$VERSION /app/build_release
    exit 0;;
esac
