name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
  - cron: 0 2 * * 3,6

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27.2'
          elixir-version: '1.18.1'

      - run: mix deps.get

      - run: mix test

      - run: mix format --check-formatted

      - run: mix credo
